import { Injectable } from '@angular/core';

export const ConstantService = {
	FETCHCLASSES: 'expert/get/class/list',
	FETCHGENDER: 'expert/get/gender',
	FETCHBOARDS: 'expert/get/board/list',
	FETCHSUBJECT: 'expert/get/subject/guidance',
	FETCHPERSONALGUIDANCE: 'expert/get/personal/guidance',
	FETCHPINCODE: 'expert/pincode',
	SIGNUP: 'expert/signup',
	USERSIGNUP: 'user/signup',

	SAVEEXPERTPROFILE: 'expert/profile',
	SAVEEXPERTEDUCATIONANDEXPERIENCE: 'expert/highest/details',
	SAVEEXPERTSERVICES: 'expert/service/offering',
	SAVEEXPERTFEE: 'expert/insert/fees',
	CREATEEXPERTSLOTS: 'expert/create/slots',
	FETCHEXPERTPROFILEDETAILS: 'expert/get/profile',
	SAVEEXPERTLISTING: 'expert/insert/list/details',
	FETCHQUALIFICATIONBYID: 'expert/get/qualification',
	FETCHEXPERIENCEBYID: 'expert/get/experience',
	LOGIN: 'user/login',
	FETCHPERSONALBYID: 'expert/get/personal',
	FETCHSUBJECTBYID: 'expert/get/subject',
	FETCHCLASSBYID: 'expert/get/class',
	FETCHBOARDBYID: 'expert/get/board',
	FETCHEXPERTLISTBYID: 'expert/get/list/details',
	FETCHFEEBYID: 'expert/get/fees',
	FETCHSLOTSBYID: 'expert/get/slots',
	FETCHUSEREXPERTDETAILS: 'user/expert/details',
	SEARCHALLUSER: 'user/search/all',
	USERSEARCH: 'user/search',
	FETCHEXPERTRESULT: 'user/search/result',
	GETEXPERTRECENTSESSION: 'expert/get/recent/session',
	GETEXPERTTRANSACTION: 'expert/get/transaction',
	UPLOADEXPEERTDOCUMENTIMAGE: 'expert/document/picture',
	UPLOADEXPERTPROFILEIMAGE: 'expert/profile/picture',
	FETCHPROFILEPITCHER: 'expert/get/picture/',
	FETCHDOCUMENTPITCHER: 'expert/get/document/',
	DELETEDOCUMENTPITCHER: 'expert/delete/document',

	ADMINGETUSER: 'admin/get/users',
	ADMINGETEXPERTS: 'admin/get/experts',
	ADMINSESSIONS: 'admin/get/all/session',
	ADMINGETRECENTSESSION: 'admin/get/recent/session',
	ADMINGETCURRENTMONTHTRANSACTION: 'admin/get/current/month/transaction',
	ADMINGETTOTALTRANSACTION: 'admin/get/total/transaction',
	ADMINGETPREVIOUSMONTHTRANSACTION: 'admin/get/previous/month/transaction',
	WELCOMEMAIL: 'expert/send/welcome/mail',
	ADMINLOGIN: 'admin/signin',
	RESERVATIONUPCOMINGSESSION: 'expert/get/upcoming/session',
	RESERVATIONPASTSESSION: 'expert/get/past/session',
	EXPERTREVIEW: 'expert/get/expert/reviews',
	SINGLESESSION: 'expert/get/single/appointment/info',
	MULTISESSION: 'expert/get/multi/appointment/info',

	USERGETPROFILE: 'user/get/profile',
	USERSAVEPROFILE: 'user/save/profile',
	USERSAVEPROFILEPITCHER: 'user/profile/picture',
	USERGETPROFILEPITCHER: 'user/get/picture/',
	USERUPCOMINGSESSION: 'user/get/upcoming/session',
	USERPASTSESSION: 'user/get/past/session',
	USERSAVEEXPERT: 'user/save/expert',
	USERGETSAVEDEXPERTS: 'user/get/saved/expert',
	USERRECENTSESSION: 'user/get/recent/session',
	USERCREATEMULTISESSION: 'user/create/multi/session',
	USERCREATESINGLESESSION: 'user/create/session',
	USERLISTFORDROPDOWN: 'admin/active/user',
	EXPERTSAVECHANNELID: 'expert/save/channel/id',
	EXPERTCREATEPAYMENT: 'new/payment',
	EXPERTGETCHANNEL: 'expert/get/channel/id',

	RESHEDULESESSION: 'user/session/reschedule',
	CANCELSESSION: 'user/session/cancel',

	SENDUSERLOGINOTP: 'user/login/otp',
	VERIFYUSERLOGINOTP: 'user/verify/otp',
	SENDUSERSIGNUPOTP: 'user/signup/otp',
	VERIFYUSERSIGNUPOTP: 'user/signup/verify',
	SENDEXPERTLOGINOTP: 'expert/login/otp',
	VERIFYEXPERTLOGINOTP: 'expert/verify/otp',
	SENDEXPERTSIGNUPOTP: 'expert/signup',
	VERIFYEXPERTSIGNUPOTP: 'expert/signup/verify',
	SEARCHEXPERT: 'user/role/subject',
	ADMINDELETEEXPERT: 'admin/delete/expert',
	ADMINAPPROVEEXPERT: 'admin/approve/expert',
	ADMINDELETEUSER: 'admin/delete/user',

	USERGETSIXTYSESSION: 'user/get/sixty/session',
	USERGETFORTYSESSION: 'user/get/forty/session',
	USERGETTWENTYSESSION: 'user/get/twenty/session',

	USERADDREVIEW: 'user/add/review',

	EXPERTLOGINRESENDOTP: 'expert/resend/otp',
	USERLOGINRESENDOTP: 'user/resend/otp',
	SIGNUPRESENDOTP: 'expert/signup/resend/otp',

	ADMININSERTCLASS: 'admin/insert/class',
	ADMININSERTBOARD: 'admin/insert/board',
	ADMININSERTSUBJECTGUIDANCE: 'admin/insert/subject/guidance',
	ADMININSERTPERSONALGUIDANCE: 'admin/insert/personal/guidance',

	ADMINDELETECLASS: 'admin/delete/class',
	ADMINDELETEBOARD: 'admin/delete/board',
	ADMINDELETESUBJECTGUIDANCE: 'admin/delete/subject',
	ADMINDELETEPERSONALGUIDANCE: 'admin/delete/personal',

	ADMINALLSESSIONDOWNLOAD: 'admin/data/all/session',
	ADMINCURRSESSIONDOWNLOAD: 'admin/data/current_month/session',
	ADMINPREVSESSIONDOWNLOAD: 'admin/data/previous_month/session',

	ADMINALLEXPERTDOWNLOAD: 'admin/data/expert',
	ADMINALLUSERDOWNLOAD: 'admin/data/user',

	ADMINCURRENTUSERDOWNLOAD: 'admin/data/current/user',
	ADMINCURRENTEXPERTDOWNLOAD: 'admin/data/current/expert',
	ADMINPREVIOUSUSERDOWNLOAD: 'admin/data/previous/user',
	ADMINPREVIOUSEXPERTDOWNLOAD: 'admin/data/previous/expert',

	EXPERTSESSIONDOWNLOAD: 'admin/data/expert/session',
	ADMINCHANGENPASSWORD: 'admin/change/password',
	ADMINSESSION: 'admin/book/session',

	PROMOCODE: 'admin/verify/promo',

	UPDATEEXPERT: 'expert/update/expert',
	FEATUREDEXPERT: 'expert/featured/expert',
	EXPERTVIDEO: 'expert/expert/video',

	USERFORSESSION: 'admin/get/users/for-sessions',
	EXPERTFORSESSION: 'admin/get/experts/for-session',
	ADMINBOOKING: 'admin/multiple/session/booking',

	WPBLOGS: 'https://gg.kormoan.in/wp-json/wp/v2/posts?_embed&offset=3&per_page=4'
};
